### Monitor & DPI
monitor=DP-1,1920x1080@144Hz,0x0,transform=normal
dpi=96

### Gaps & Padding
general_gaps_outside=10
general_gaps_inside=5
padding_top=20
padding_bottom=30

### Workspaces
workspace=1,
workspace=2,
workspace=3,
workspace=4,

### Keybinds
bind=ALT+SPACE, exec, rofi -show drun

bind=CTRL+LEFT, workspace, -1
bind=CTRL+RIGHT, workspace, +1

bind=ALT+UP, movewindow, up
bind=ALT+DOWN, movewindow, down
bind=ALT+LEFT, movewindow, left
bind=ALT+RIGHT, movewindow, right

bind=ALT+P, exec, firefox
bind=ALT+I, exec, thunar
bind=ALT+O, exec, obsidian
bind=ALT+E, exec, hyprctl dispatch workspace next

### Autostart
exec-once = waybar
